### ISSUE TITLE
여기에도 gh-pages 브랜치가 없어도 될 것 같습니다.

### ISSUE THREAD

**Issue by Namnamseo** [gshslatexintro/latex-course#3]
포크 전의 리포지터리에 있었던 브랜치이고, 포크 이후로도 쓸모가 없어 커밋이 없습니다.
`gh-pages` 브랜치를 지워도 될 것 같다고 생각합니다.

지울 거라면 딱히 상관은 없긴 한데, [해당 GitHub Pages 사이트](https://gshslatexintro.github.io/latex-course-ko/)가 접속이 되질 않네요. 리포지터리 설정은 되어있는데......

**Comment by seungwonpark** [comment]
헐. 포크할 때 gh-pages 브랜치가 딸려왔을 줄은 몰랐네요.
딱히 이 레포지토리에 해당되는 GitHub Pages 사이트를 만드려고 했던 것도 아니니, 삭제해도 될 것 같습니다.

**Comment by Namnamseo** [comment]
삭제하였습니다. GitHub Pages 옵션은 자동으로 해제되었습니다.
